# .github/dependabot.yml

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"                # 根目錄為 .github/workflows/
    schedule:
      interval: "weekly"
    labels:
      - dependencies
      - github-actions
    open-pull-requests-limit: 5
    rebase-strategy: auto
