version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"  # 根目錄含 pyproject.toml
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    labels:
      - "dependencies"
      - "security"

  - package-ecosystem: "github-actions"
    directory: "/"  # 掃 .github/workflows/
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    rebase-strategy: "auto"
    labels:
      - "CI"
      - "security"
